apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kindnet
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - get
      - list
      - patch
      - watch
      - update
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - watch
      - delete
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["", "events.k8s.io"]
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups: ["security.openshift.io"]
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged
  - apiGroups: [""]
    resources:
      - "nodes/status"
    verbs:
      - patch
      - update
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups: ['authentication.k8s.io']
    resources: ['tokenreviews']
    verbs: ['create']
  - apiGroups: ['authorization.k8s.io']
    resources: ['subjectaccessreviews']
    verbs: ['create']